on: push
jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps: 
    - Step one
      uses: actions/checkout@v2
    - Step two
      run: env | sort

  job2:
    name: Second job
    runs-on: windows-latest
    steps: 
    - Step one
      uses: actions/checkout@v2
    - Step two
    run: "Get-ChildItem Env: | Sort-Object Name"